--select * from dbo.customer_shopping_behavior;

--What is the total revenue generated by male customers compared to female customers?
select gender,sum(purchase_amount) as Total_Revenue 
from dbo.customer_shopping_behavior group by gender;

--Which customers use discounts but still spend more than the average purchase amount?
SELECT customer_id, purchase_amount
FROM dbo.customer_shopping_behavior
WHERE discount_applied = 'yes'
  AND purchase_amount >
      (SELECT AVG(purchase_amount)
       FROM dbo.customer_shopping_behavior);

--Which are the top five products with the highest average revenue rating?
select top 5 item_purchased, avg(review_rating)
as Average_Product_Rating   
from dbo.customer_shopping_behavior group by item_purchased
order by Average_Product_Rating desc;

--Compare the average purchase amounts between Standard Shipping and Express Shipping.
select shipping_type,avg(purchase_amount) as Total_Revenue 
from dbo.customer_shopping_behavior 
where shipping_type in('Standard','Express')
group by shipping_type;

--Do subscribed customers spend more? compare average spend and total revenue.
select subscription_status,count(customer_id) as total_customers,
avg(purchase_amount) as Avg_Revenue ,
sum(purchase_amount) as sum_Revenue
from dbo.customer_shopping_behavior group by subscription_status
order by sum_Revenue, Avg_Revenue

--Which five products have the highest percentage of purchases made with discounts applied?
SELECT TOP 5
    item_purchased,
    ROUND(100.0 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)
        / COUNT(*),
        2
    ) AS discount_percentage
FROM dbo.customer_shopping_behavior
GROUP BY item_purchased
ORDER BY discount_percentage DESC;

--Segment customers based on their returning status and loyalty, and calculate the total number of purchases and the net amount spent for each segment.
WITH customer_type AS (
    SELECT
        customer_id,purchase_amount,
        CASE 
            WHEN previous_purchases = 1 THEN 'New'
            WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
            ELSE 'Loyal'
        END AS customer_segment
    FROM dbo.customer_shopping_behavior
)
SELECT
    customer_segment,COUNT(*) AS total_purchases,SUM(purchase_amount) AS net_amount_spent
FROM customer_type GROUP BY customer_segment;

--What are the top three most purchased products within each category?
with item_count as (
select category, item_purchased , count(customer_id) as total_orders,
row_number() over (partition by category order by count(customer_id) desc) as item_rank
from dbo.customer_shopping_behavior
group by category,item_purchased
)
select item_rank, category, item_purchased, total_orders from item_count

--Are customers who make repeat purchases (more than five previous purchases) also more likely to subscribe?
SELECT subscription_status,
       COUNT(customer_id) AS repeat_buyers
FROM dbo.customer_shopping_behavior
WHERE previous_purchases > 5
GROUP BY subscription_status;

--What is the revenue contribution of each customer group?
SELECT age_group,
       sum(purchase_amount) AS total_amount
FROM dbo.customer_shopping_behavior
GROUP BY age_group
order by total_amount desc;
